### ISSUE TITLE
Hanya 1x sukses

### ISSUE THREAD

**Issue by Achik72** [ClayHackerTeam/Prankers#1]
SpamCall nya cuma sekali aja , apakah ada masalah atau kesalahan ??

**Comment by mansurabbas** [comment]
[?] Masukan No Target ==> 2348034451240                               [?] Mode Banyak (y/n) ==> y
[?] JumlahSpam Korban ==> 3
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /root/Desktop/Prankers/311/SpamCall.php(8) : eval()'d code:11   Stack trace:
#0 /root/Desktop/Prankers/311/SpamCall.php(8) : eval()'d code(11): prankcall->loop('3')
#1 /root/Desktop/Prankers/311/SpamCall.php(8) : eval()'d code(25): prankcall->run()
#2 /root/Desktop/Prankers/311/SpamCall.php(8): eval()
#3 {main}
  thrown in /root/Desktop/Prankers/311/SpamCall.php(8) : eval()'d code on line 11

**Comment by mansurabbas** [comment]
Nomer dimulai dari 62..
Masukkan Nomer  : 8034451240                                          Jumlah  Bom     : 3
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /root/Desktop/Prankers/caping-spam/run.php:7                    Stack trace:                                                          #0 /root/Desktop/Prankers/caping-spam/run.php(31): bom('8034451240')
#1 {main}                                                               thrown in /root/Desktop/Prankers/caping-spam/run.php on line 7

**Comment by merxas47** [comment]
cONTAcTs turkey does not cause please help

**Comment by merxas47** [comment]
help please
